# Generated by Django 5.2.1 on 2025-05-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merch',
            old_name='SKU',
            new_name='barcode',
        ),
        migrations.RenameField(
            model_name='merch',
            old_name='UPC',
            new_name='product_code',
        ),
    ]
